spring.application.name=date-anya
server.port=8080

# Email (заполни свои SMTP-данные)
spring.mail.host=smtp.mail.ru
spring.mail.port=587
spring.mail.username=extraponcho02@mail.ru
spring.mail.password=LEvVMKtYidsSckUdolTn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email отправителя (куда придут отзывы девушек)
app.system.email=extraponcho02@mail.ru
